#ifndef CASTLE_GROUNDS_HEADER_H
#define CASTLE_GROUNDS_HEADER_H
#include "types.h"
#include "game/moving_texture.h"
extern const GeoLayout Geo_castle_grounds_1_0x14ac080[];
extern Gfx DL_castle_grounds_1_0xe039910[];
extern Gfx DL_castle_grounds_1_0xe043198[];
extern Gfx DL_castle_grounds_1_0xe043450[];
extern const Collision col_castle_grounds_1_0xe044640[];
extern struct MovtexQuadCollection castle_grounds_1_Movtex_0[];
extern struct MovtexQuadCollection castle_grounds_1_Movtex_1[];
extern struct MovtexQuadCollection castle_grounds_1_Movtex_2[];
extern const GeoLayout Geo_castle_grounds_2_0x14abf70[];
extern Gfx DL_castle_grounds_2_0xe00e260[];
extern Gfx DL_castle_grounds_2_0xe010e60[];
extern const Collision col_castle_grounds_2_0xe010fd0[];
extern struct MovtexQuadCollection castle_grounds_2_Movtex_0[];
extern struct MovtexQuadCollection castle_grounds_2_Movtex_1[];
extern struct MovtexQuadCollection castle_grounds_2_Movtex_2[];
extern const GeoLayout Geo_castle_grounds_3_0x14abe60[];
extern Gfx DL_castle_grounds_3_0xe00b2e0[];
extern Gfx DL_castle_grounds_3_0xe00d768[];
extern const Collision col_castle_grounds_3_0xe00d870[];
extern struct MovtexQuadCollection castle_grounds_3_Movtex_0[];
extern struct MovtexQuadCollection castle_grounds_3_Movtex_1[];
extern struct MovtexQuadCollection castle_grounds_3_Movtex_2[];
extern const LevelScript level_castle_grounds_custom_entry[];
extern const LevelScript local_area_castle_grounds_1_[];
extern const LevelScript local_objects_castle_grounds_1_[];
extern const LevelScript local_warps_castle_grounds_1_[];
extern const LevelScript local_area_castle_grounds_2_[];
extern const LevelScript local_objects_castle_grounds_2_[];
extern const LevelScript local_warps_castle_grounds_2_[];
extern const LevelScript local_area_castle_grounds_3_[];
extern const LevelScript local_objects_castle_grounds_3_[];
extern const LevelScript local_warps_castle_grounds_3_[];
extern const LevelScript level_castle_grounds_entry[];
extern const GeoLayout castle_grounds_geo_000660[];
extern const GeoLayout castle_grounds_geo_0006F4[];
extern const GeoLayout castle_grounds_geo_00070C[];
extern const GeoLayout castle_grounds_geo_000724[];
extern const GeoLayout castle_grounds_geo_00073C[];
extern const Gfx castle_grounds_seg7_dl_07006D70[];
extern const Gfx castle_grounds_seg7_dl_070095F0[];
extern const Gfx castle_grounds_seg7_dl_0700A290[];
extern const Gfx castle_grounds_seg7_dl_0700A860[];
extern const Gfx castle_grounds_seg7_dl_0700B1D0[];
extern const Gfx castle_grounds_seg7_dl_0700BA20[];
extern const Gfx castle_grounds_seg7_dl_0700BB80[];
extern const Gfx castle_grounds_seg7_dl_0700BC68[];
extern const Gfx castle_grounds_seg7_dl_0700C210[];
extern const Gfx castle_grounds_seg7_dl_0700C430[];
extern const Gfx castle_grounds_seg7_dl_0700C670[];
extern const Gfx castle_grounds_seg7_dl_0700C6A8[];
extern const Gfx castle_grounds_seg7_dl_0700C6E8[];
extern const Gfx castle_grounds_seg7_dl_0700C728[];
extern const Gfx castle_grounds_seg7_dl_0700C768[];
extern const struct Animation *const castle_grounds_seg7_anims_flags[];
extern const Gfx castle_grounds_seg7_dl_0700EA58[];
extern const Gfx castle_grounds_seg7_us_dl_0700F2E8[];
extern const Collision castle_grounds_seg7_collision_level[];
extern const MacroObject castle_grounds_seg7_macro_objs[];
extern const Collision castle_grounds_seg7_collision_moat_grills[];
extern const Collision castle_grounds_seg7_collision_cannon_grill[];
extern const struct MovtexQuadCollection castle_grounds_movtex_water[];
extern Movtex castle_grounds_movtex_tris_waterfall[];
extern const Gfx castle_grounds_dl_waterfall[];
extern const LevelScript level_castle_grounds_entry[];
#endif